### ISSUE TITLE
Nothing is showing up in the queue

### ISSUE THREAD

**Issue by VGBoy** [antsstyle/artretweeter#1]
I've recently tried using this to boost my tweets, but when I look at the queue the day after I adjusted the settings, it says it's empty.

**Comment by antsstyle** [comment]
It will do shortly. The app exceeded its Twitter limits until March 28, so it wasn't able to pick up new tweets until now (and I wasn't awake to re-adjust the cronjobs xD)

**Comment by antsstyle** [comment]
You should find that it's working now, but if it isn't, let me know.
