### ISSUE TITLE
Won't let me sign in

### ISSUE THREAD

**Issue by VGBoy** [antsstyle/artretweeter#2]
I tried logging in on the website because I noticed some of my tweets haven't been retweeted by the app recently, and it keeps resetting me to the home page as if I haven't logged in.

**Comment by antsstyle** [comment]
It's due to a server problem, I think. I'm waiting for the hosting provider to resolve it, should be sometime today so I'll let you know ^^

**Comment by antsstyle** [comment]
It's back up now, I fixed it myself. Let me know if it's still failing.
